#! Load ytt libs
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

#! export vendored contour bundle as a var
#@ kapp_controller_lib = library.get("bundle/config")

#@ def kapp_controller_values():
#@overlay/match-child-defaults missing_ok=True
namespace: #@ data.values.namespace
#@overlay/match-child-defaults missing_ok=True
nodeSelector: #@ data.values.nodeSelector
#@overlay/match-child-defaults missing_ok=True
deployment: #@ data.values.deployment
#@overlay/match-child-defaults missing_ok=True
daemonset: #@ data.values.daemonset
#@overlay/match-child-defaults missing_ok=True
kappController:  #@ data.values.kappController
#@ end

#! render yaml from vendored lib with data values
--- #@ template.replace(kapp_controller_lib.with_data_values(kapp_controller_values()).eval())
