#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespace: kapp-controller
nodeSelector: null
deployment:
  updateStrategy: null
  rollingUpdate:
    maxUnavailable: null
    maxSurge: null
daemonset:
  updateStrategy: null
kappController:
  namespace: null
  createNamespace: true
  globalNamespace: tanzu-package-repo-global
  #! The psp names that kapp-controller will use in its clusterrole.rules. Leave it empty if psp is not enabled
  pspNames: ["vmware-system-privileged"]
  deployment:
    #! The coreDNSIP will be injected into /etc/resolv.conf of kapp-controller pod
    coreDNSIP: null
    hostNetwork: false
    priorityClassName: null
    concurrency: 4
    tolerations: []
    apiPort: 10350
    metricsBindAddress: ":8080"
  config:
    caCerts: ""
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
    dangerousSkipTLSVerify: ""
