---
swagger: "2.0"
info:
  description: "Swagger API definition for the insurance apis"
  version: "0.0.2"
  title: "APIs to interact with insurance external systems"
host: insurance.gns.dekt.io
basePath: "/v1"
tags:
- name: "Data collection"
  description: "Data collection (read-only) APIs"
- name: "Data manipulation"
  description: "Data manipulation (write) APIs"
schemes:
- "https"
paths:
  /list-providers:
    get:
      tags:
      - "Data collection"
      summary: "List available insurance providers"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful data collection"
        400:
          description: "Invalid candidate identifier"
  /process-claim/{cadidateID}:
    post:
      tags:
      - "Data manipulation"
      summary: "Process a new insurance claim"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cadidateID"
        in: "path"
        description: "ID of candidate to update data for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful data collection"
        400:
          description: "Invalid candidate identifier"