---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db
type: Opaque
stringData:
  type: postgresql
  provider: azure
  host: "[CHANGE_ME].database.windows.net"
  port: "1433"
  database: "sensors-inventory"
  username: "[CHANGE_ME]"
  password: "[CHANGE_ME]"