#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ def parse_resource_psp_names(kappControllerSpec):
#@   if not hasattr(kappControllerSpec, "pspNames") or kappControllerSpec.pspNames == None:
#@     return []
#@   end
#@   return kappControllerSpec.pspNames
#@ end

#@ pspNames = parse_resource_psp_names(data.values.kappController)

#@ if pspNames:
#@overlay/match by=overlay.subset({"kind": "ClusterRole", "metadata": {"name": "kapp-controller-cluster-role"}}),expects="1+"
---
rules:
  #@overlay/append
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames: #@ parse_resource_psp_names(data.values.kappController)
#@ end