apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/source-test-scan-to-url;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterSupplyChain","metadata":{"labels":{"kapp.k14s.io/app":"1657307330139182118","kapp.k14s.io/association":"v1.8c64ddca205b2ba4c71428ca92333680"},"name":"source-test-scan-to-url"},"spec":{"params":[{"name":"maven_repository_url","value":"https://repo.maven.apache.org/maven2"},{"default":"main","name":"gitops_branch"},{"default":"supplychain","name":"gitops_user_name"},{"default":"supplychain","name":"gitops_user_email"},{"default":"supplychain@cluster.local","name":"gitops_commit_message"},{"default":"","name":"gitops_ssh_secret"}],"resources":[{"name":"source-provider","params":[{"name":"serviceAccount","value":"default"},{"name":"gitImplementation","value":"go-git"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-template"}},{"name":"deliverable","params":[{"name":"registry","value":{"ca_cert_data":"","repository":"dekt-stage","server":"harbor.apps.cf.tanzutime.com"}}],"templateRef":{"kind":"ClusterTemplate","name":"deliverable-template"}},{"name":"source-tester","sources":[{"name":"source","resource":"source-provider"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"testing-pipeline"}},{"name":"source-scanner","params":[{"default":"scan-policy","name":"scanning_source_policy"},{"default":"blob-source-scan-template","name":"scanning_source_template"}],"sources":[{"name":"source","resource":"source-tester"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-scanner-template"}},{"name":"image-builder","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"ca_cert_data":"","repository":"dekt-stage","server":"harbor.apps.cf.tanzutime.com"}},{"default":"default","name":"clusterBuilder"},{"default":"./Dockerfile","name":"dockerfile"},{"default":"./","name":"docker_build_context"},{"default":[],"name":"docker_build_extra_args"}],"sources":[{"name":"source","resource":"source-scanner"}],"templateRef":{"kind":"ClusterImageTemplate","options":[{"name":"kpack-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"DoesNotExist"}]}},{"name":"kaniko-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"Exists"}]}}]}},{"images":[{"name":"image","resource":"image-builder"}],"name":"image-scanner","params":[{"default":"scan-policy","name":"scanning_image_policy"},{"default":"private-image-scan-template","name":"scanning_image_template"}],"templateRef":{"kind":"ClusterImageTemplate","name":"image-scanner-template"}},{"images":[{"name":"image","resource":"image-scanner"}],"name":"config-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterConfigTemplate","name":"convention-template"}},{"configs":[{"name":"config","resource":"config-provider"}],"name":"app-config","templateRef":{"kind":"ClusterConfigTemplate","name":"config-template"}},{"configs":[{"name":"config","resource":"app-config"}],"name":"config-writer","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"ca_cert_data":"","repository":"dekt-stage","server":"harbor.apps.cf.tanzutime.com"}}],"templateRef":{"kind":"ClusterTemplate","name":"config-writer-template"}}],"selector":{"apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2022-07-08T19:08:50Z"
  generation: 1
  labels:
    kapp.k14s.io/app: "1657307330139182118"
    kapp.k14s.io/association: v1.8c64ddca205b2ba4c71428ca92333680
  name: dekt-src-to-api
  resourceVersion: "711735"
  uid: 95f7e0d7-7ab6-4dbf-88ea-4d1451a18bd6
spec:
  selector:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: dekt-backend
  params:
  - name: maven_repository_url
    value: https://repo.maven.apache.org/maven2
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: deliverable
    params:
    - name: registry
      value:
        ca_cert_data: ""
        repository: [CHANGE_ME]
        server: [CHANGE_ME]
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: source-tester
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
  - name: image-builder
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: [CHANGE_ME]
        server: [CHANGE_ME]
    - default: default
      name: clusterBuilder
    - default: ./Dockerfile
      name: dockerfile
    - default: ./
      name: docker_build_context
    - default: []
      name: docker_build_extra_args
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: kpack-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: DoesNotExist
      - name: kaniko-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: Exists
  - images:
    - name: image
      resource: image-builder
    name: conventions
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: conventions
    name: bind-services
    templateRef:
      kind: ClusterConfigTemplate
      name: config-template
  - configs:
    - name: config
      resource: bind-services
    name: deploy-app
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        ca_cert_data: ""
        repository: [CHANGE_ME]
        server: [CHANGE_ME]
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
status:
  conditions:
  - lastTransitionTime: "2022-07-08T19:08:50Z"
    message: ""
    reason: Ready
    status: "True"
    type: TemplatesReady
  - lastTransitionTime: "2022-07-08T19:08:50Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  observedGeneration: 1
