apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: googlesql-binder
spec:
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")

    !@ Binding to Google SQL instance using Crossplane
    !@
    !@ Assumptions
    !@ 1. Crossplane installed
    !@ 2. ProviderConfig configured to Google SQL
    !@ 3. Google PostgreSQL Instance instance provisioned
    !@
    apiVersion: apiextensions.crossplane.io/v1
    kind: Composition
    metadata:
      name: dekt-googlesql-binder
      labels:
        provider: dekt-provider-gcp
        vpc: dekt-vpc-data-services
    spec:
      writeConnectionSecretsToNamespace: crossplane-system
      compositeTypeRef:
        apiVersion: database.example.org/v1alpha1
        kind: CompositePostgreSQLInstance
      resources:
        - name: data.values.workload.metadata.dbName
          base:
            apiVersion: database.gcp.crossplane.io/v1beta1
            kind: CloudSQLInstance
            metadata:
              name: example-cloudsql-instance
            spec:
              forProvider:
                databaseVersion: POSTGRES_11
                region: us-west2
                settings:
                  tier: db-custom-1-3840
                  dataDiskSizeGb: 20
              providerConfigRef:
                name: example
              writeConnectionSecretToRef:
                name: example-cloudsql-connection-details
                namespace: crossplane-system
          connectionDetails:
            - fromConnectionSecretKey: username
            - fromConnectionSecretKey: password
            - fromConnectionSecretKey: endpoint
            - fromConnectionSecretKey: port
