apiVersion: v1
imagePullSecrets:
- name: scanner-secret-ref
kind: ServiceAccount
metadata:
  name: grype-scanner
secrets:
- name: registry-credentials
- name: git-ssh
- name: store-ca-cert
- name: store-auth-token
