apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: donations-routes-config
spec:
  service: 
    name: donations-api
  routes:
    - predicates:
        - Path=/list-donations
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-donation/{personID}/donation/{donationDetails}
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="donationsCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: v1
kind: Service
metadata:
  name: donations-api
spec:
  ports:
    - port: 80
      targetPort: 80
