apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brownfield-apis

resources:
  - datacheck.yaml
  - donations.yaml
  - suppliers.yaml
  - insurance.yaml
  - payments.yaml
  - sms.yaml
  - locations.yaml
  - sentiment.yaml
  - tsm-generated-config.yaml
  

  



  