apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: sms-routes-config
spec:
  service: 
    name: sms-api
  routes:
    - predicates:
        - Path=/list-sms
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-donation/*/adoption-request/**
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="smsCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: v1
kind: Service
metadata:
  name: sms-api
spec:
  ports:
    - port: 80
      targetPort: 80
