#! Load ytt libs
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

#! export vendored secretgen bundle as a var
#@ secretgen_controller_lib = library.get("bundle/config")

#@ def secretgen_controller_values():
#@overlay/match-child-defaults missing_ok=True
nodeSelector: #@ data.values.nodeSelector
#@overlay/match-child-defaults missing_ok=True
deployment: #@ data.values.deployment
#@overlay/match-child-defaults missing_ok=True
daemonset: #@ data.values.daemonset
#@overlay/match-child-defaults missing_ok=True
secretgenController:  #@ data.values.secretgenController
#@ end

#! render yaml from vendored lib with data values
--- #@ template.replace(secretgen_controller_lib.with_data_values(secretgen_controller_values()).eval())
