#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ def parse_resource_psp_names(secretgenControllerSpec):
#@   if not hasattr(secretgenControllerSpec, "pspNames") or secretgenControllerSpec.pspNames == None:
#@     return []
#@   end
#@   return secretgenControllerSpec.pspNames
#@ end

#@ pspNames = parse_resource_psp_names(data.values.secretgenController)

#@ if pspNames:
#@overlay/match by=overlay.subset({"kind": "ClusterRole", "metadata": {"name": "secretgen-controller-cluster-role"}}),expects="1+"
---
rules:
  #@overlay/append
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames: #@ parse_resource_psp_names(data.values.secretgenController)
#@ end