#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if hasattr(data.values, "secretgenController"):
#@   if hasattr(data.values.secretgenController, "namespace"):
#@     ns = data.values.secretgenController.namespace
#@   else:
#@     ns = "secretgen-controller"
#@   end
#@ else:
#@   # copied from /values.star
#@   if hasattr(data.values.kappController, "namespace") and data.values.kappController.namespace:
#@     ns = data.values.kappController.namespace
#@   else:
#@     ns = data.values.namespace
#@   end
#@ end

#@ secret_name = ns + "-registry-creds"

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret_name
  namespace: #@ ns
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(data.values.registry.username, data.values.registry.password))
  #@ docker_creds = {"username": data.values.registry.username, "password": data.values.registry.password, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.registry.server: docker_creds}}))

#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
      - name: #@ secret_name
